package coupon

const ERROR_COUPON = 0x80000

const ERROR_COUPON_NOT_FOUND = ERROR_COUPON + 1

const ERROR_COUPON_COUNT = ERROR_COUPON + 2

const ERROR_COUPON_NOT_FOUND_ID = ERROR_COUPON + 3

const ERROR_COUPON_NOT_FOUND_UID = ERROR_COUPON + 4

const ERROR_COUPON_UCOUNT = ERROR_COUPON + 5

const ERROR_COUPON_STATUS = ERROR_COUPON + 6

const ERROR_COUPON_TIME = ERROR_COUPON + 7

const ERROR_COUPON_VALUE = ERROR_COUPON + 8
